function header1(){document.writeln("<div id=\'preloader\'></div>");
	document.writeln("    ");
	document.writeln("	<!-- ================================-->");
	document.writeln("    <div class=\'header_top\'>");
	document.writeln("        <!-- Logo -->");
	document.writeln("        <div class=\'container\'>");
	document.writeln("            <div class=\'row\'>");
	document.writeln("                <div class=\'header_top_location\'>");
	document.writeln("                    <div class=\'header_top_left\'>");
	document.writeln("                        <ul class=\'list-inline pull-left\'>");
	document.writeln("							<li><i class=\'fa fa-bookmark\'></i>西南交通大学，成都，中国</li>");
	document.writeln("                        </ul>");
	document.writeln("                    </div>");
	document.writeln("                    <div class=\'header_top_right list-unstyled\'>");
	document.writeln("                        <ul>");
	document.writeln("							<li><i class=\'fa fa-envelope\' ></i><a href=\'mailto:846972585@qq.com\'>846972585@qq.com</a></li>");
	document.writeln("                            <li><i class=\'fa fa-phone\'></i>+86 158 8227 4210</li>");
	document.writeln("                        </ul>");
	document.writeln("                    </div>");
	document.writeln("                </div>");
	document.writeln("            </div>");
	document.writeln("        </div>");
	document.writeln("    </div>");
	document.writeln("");
	document.writeln("	<div class=\'navigation\'>");
	document.writeln("        <div class=\'container\'>");
	document.writeln("            <div class=\'row\'>");
	document.writeln("                <div class=\'header_logo\'>");
	document.writeln("                    <a href=\'#\'><img src=\'images/logo.png\' alt=\'\'>");
	document.writeln("                    </a>");
	document.writeln("                </div>");
	document.writeln("                <div id=\'navigation\'>");
document.writeln("                    <ul>");}
function header2(){document.writeln("                    </ul>");
	document.writeln("                </div>");
	document.writeln("                <div class=\'header-right\'>");
	document.writeln("                    <a href=\'mailto:846972585@qq.com\' class=\'header_quate_right\'>联系我们</a>");
	document.writeln("                </div>");
	document.writeln("                <!-- End: social-nav -->");
	document.writeln("            </div>");
	document.writeln("        </div>");
document.writeln("    </div>");}
function footer(){
	document.writeln("	<footer class=\'footer-section\'>");
	document.writeln("");
	document.writeln("		<div class=\'base-header\' id=\'testimo\'>");
	document.writeln("			<img src=\'images/heading_icon.png\' alt=\'\'>");
	document.writeln("		</div>");
	document.writeln("		<div class=\'container\'>");
	document.writeln("			<div class=\'row\'>");
	document.writeln("");
	document.writeln("				<div class=\'col-sm-3 col-xs-12\'>");
	document.writeln("					<div class=\'widget\'>");
	document.writeln("						<div class=\'col-md-12\'>");
	document.writeln("							<img class=\'img-responsive\' src=\'images/logo.png\' alt=\'\'>");
	document.writeln("						</div>");
	document.writeln("						<div class=\'col-xs-1\'><br>");
	document.writeln("							<ul class=\'list-icons link-list footer_soc\'>");
	document.writeln("								<li>");
	document.writeln("									<a><i class=\'fa fa-bolt\'></i></a>");
	document.writeln("								</li>");
	document.writeln("								<li>");
	document.writeln("									<a><i class=\'fa fa-bolt\'></i></a>");
	document.writeln("								</li>");
	document.writeln("								<li>");
	document.writeln("									<a><i class=\'fa fa-bolt\'></i></a>");
	document.writeln("								</li>");
	document.writeln("							</ul>");
	document.writeln("						</div>");
	document.writeln("						<div class=\'col-xs-10\'><br>");
	document.writeln("							<p class=\'footer_para\'>精心设计<br>投入精力<br>希望满意</p>");
	document.writeln("						</div>");
	document.writeln("					</div>");
	document.writeln("				</div>");
	document.writeln("");
	document.writeln("");
	document.writeln("");
	document.writeln("");
	document.writeln("				<div class=\'col-sm-3 col-xs-12\'>");
	document.writeln("					<div class=\'widget\'>");
	document.writeln("						<h5>指导教师</h5>");
	document.writeln("						<ul class=\'footer_contact_info\'>");
	document.writeln("							<li><i class=\'icon_profile\'></i><span><a>王衡</a></span></li>");
	document.writeln("							<li><i class=\'icon_profile\'></i><span><a>李君</a></span></li>");
	document.writeln("						</ul>");
	document.writeln("					</div>");
	document.writeln("				</div>");
	document.writeln("");
	document.writeln("");
	document.writeln("				<div class=\'col-sm-3 col-xs-12\'>");
	document.writeln("					<div class=\'widget\'>");
	document.writeln("						<h5>小组成员</h5>");
	document.writeln("						<ul class=\'footer_contact_info\'>");
	document.writeln("							<li><i class=\'icon_profile\'></i><span><a href=\'contact.html#zmh\'>朱敏华</a></span></li>");
	document.writeln("							<li><i class=\'icon_profile\'></i><span><a href=\'contact.html#ljx\'>刘佳欣</a></span></li>");
	document.writeln("							<li><i class=\'icon_profile\'></i><span><a href=\'contact.html#hbj\'>韩宝佳</a></span></li>");
	document.writeln("							<li><i class=\'icon_profile\'></i><span><a href=\'contact.html#glb\'>高立博</a></span></li>");
	document.writeln("							<li><i class=\'icon_profile\'></i><span><a href=\'contact.html#hck\'>黄崇凯</a></span></li>");
	document.writeln("						</ul>");
	document.writeln("					</div>");
	document.writeln("				</div>");
	document.writeln("");
	document.writeln("				<div class=\'col-sm-3 col-xs-12\'>");
	document.writeln("					<div class=\'widget\'>");
	document.writeln("						<h5>联系方式</h5>");
	document.writeln("						<!-- Start Subscribe -->");
	document.writeln("						<div class=\'box-content\'>");
	document.writeln("							<div class=\'cont_widg\'>");
	document.writeln("								<ul class=\'footer_contact_info\'>");
	document.writeln("									<li><i class=\'icon_phone\'></i><span>+86 158 8227 4210</span>");
	document.writeln("									</li>");
	document.writeln("									<li><em class=\'icon_mail\'></em><span><a href=\'mailto:846972585@qq.com\'>846972585@qq.com</a></span> </li>");
	document.writeln("									<li><i class=\'icon_pin\'></i><span>西南交通大学, 成都, 四川, 中国</span>");
	document.writeln("									</li>");
	document.writeln("									<li><i class=\'icon_clock\'></i><span>周一至周五 09:00-23:00</span>");
	document.writeln("									</li>");
	document.writeln("								</ul>");
	document.writeln("							</div>");
	document.writeln("						</div>");
	document.writeln("					</div>");
	document.writeln("				</div>");
	document.writeln("");
	document.writeln("");
	document.writeln("				<div class=\'subfooter\'>");
	document.writeln("					<div class=\'col-xs-6\'>");
	document.writeln("						<p>Copyright &copy; 2018.SWJTU All rights reserved.</p>");
	document.writeln("					</div>");
	document.writeln("					<div class=\'col-xs-6\'>");
	document.writeln("						<a class=\'scrollup\'><i class=\'arrow_carrot-up\'></i></a>");
	document.writeln("					</div>");
	document.writeln("				</div>");
	document.writeln("");
	document.writeln("			</div>");
	document.writeln("		</div>");
	document.writeln("	</footer>");
	document.writeln("");
	document.writeln("");
	document.writeln("	<script src=\'js/jquery-1.12.4.min.js\'></script>");
	document.writeln("	<script src=\'js/plugins.js\'></script>");
	document.writeln("	<script src=\'js/bootstrap.min.js\'></script>");
	document.writeln("");
	document.writeln("	<script src=\'js/main.js\'></script>");
	document.writeln("");
	document.writeln("");
	document.writeln("</body>");
	document.writeln("");
	document.writeln("</html>");
	document.writeln("");
}