# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ListItemWidget.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_item(object):
    def setupUi(self, item):
        item.setObjectName("item")
        item.setWindowModality(QtCore.Qt.WindowModal)
        item.resize(570, 144)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(item.sizePolicy().hasHeightForWidth())
        item.setSizePolicy(sizePolicy)
        item.setStyleSheet("border-color: rgb(0, 0, 255);")
        self.gridLayout = QtWidgets.QGridLayout(item)
        self.gridLayout.setContentsMargins(2, 2, 2, 2)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(item)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: rgb(235, 217, 255);")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_school = QtWidgets.QHBoxLayout()
        self.horizontalLayout_school.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_school.setObjectName("horizontalLayout_school")
        self.label_num = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_num.sizePolicy().hasHeightForWidth())
        self.label_num.setSizePolicy(sizePolicy)
        self.label_num.setStyleSheet("font: 25 12pt \"Adobe 宋体 Std L\";")
        self.label_num.setObjectName("label_num")
        self.horizontalLayout_school.addWidget(self.label_num)
        self.lable_university = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lable_university.sizePolicy().hasHeightForWidth())
        self.lable_university.setSizePolicy(sizePolicy)
        self.lable_university.setStyleSheet("font: 18pt \"Adobe 黑体 Std R\";")
        self.lable_university.setObjectName("lable_university")
        self.horizontalLayout_school.addWidget(self.lable_university, 0, QtCore.Qt.AlignBottom)
        self.label_level = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_level.sizePolicy().hasHeightForWidth())
        self.label_level.setSizePolicy(sizePolicy)
        self.label_level.setStyleSheet("")
        self.label_level.setObjectName("label_level")
        self.horizontalLayout_school.addWidget(self.label_level, 0, QtCore.Qt.AlignBottom)
        self.label_condition = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_condition.sizePolicy().hasHeightForWidth())
        self.label_condition.setSizePolicy(sizePolicy)
        self.label_condition.setObjectName("label_condition")
        self.horizontalLayout_school.addWidget(self.label_condition)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_school.addItem(spacerItem)
        self.label_score = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_score.sizePolicy().hasHeightForWidth())
        self.label_score.setSizePolicy(sizePolicy)
        self.label_score.setStyleSheet("font: 25 11pt \"Adobe 宋体 Std L\";")
        self.label_score.setObjectName("label_score")
        self.horizontalLayout_school.addWidget(self.label_score)
        self.label_evaluation = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_evaluation.sizePolicy().hasHeightForWidth())
        self.label_evaluation.setSizePolicy(sizePolicy)
        self.label_evaluation.setStyleSheet("font: 75 12pt \"等线\";")
        self.label_evaluation.setObjectName("label_evaluation")
        self.horizontalLayout_school.addWidget(self.label_evaluation)
        self.verticalLayout.addLayout(self.horizontalLayout_school)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_proCode = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_proCode.sizePolicy().hasHeightForWidth())
        self.label_proCode.setSizePolicy(sizePolicy)
        self.label_proCode.setObjectName("label_proCode")
        self.horizontalLayout_3.addWidget(self.label_proCode)
        self.label_proName = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_proName.sizePolicy().hasHeightForWidth())
        self.label_proName.setSizePolicy(sizePolicy)
        self.label_proName.setStyleSheet("font: 10pt \"Adobe 黑体 Std R\";")
        self.label_proName.setObjectName("label_proName")
        self.horizontalLayout_3.addWidget(self.label_proName)
        self.label_school = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_school.sizePolicy().hasHeightForWidth())
        self.label_school.setSizePolicy(sizePolicy)
        self.label_school.setObjectName("label_school")
        self.horizontalLayout_3.addWidget(self.label_school)
        self.proDirection = QtWidgets.QTextBrowser(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proDirection.sizePolicy().hasHeightForWidth())
        self.proDirection.setSizePolicy(sizePolicy)
        self.proDirection.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.proDirection.setObjectName("proDirection")
        self.horizontalLayout_3.addWidget(self.proDirection)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_retest = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_retest.sizePolicy().hasHeightForWidth())
        self.label_retest.setSizePolicy(sizePolicy)
        self.label_retest.setObjectName("label_retest")
        self.verticalLayout_2.addWidget(self.label_retest)
        self.label_pretest = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pretest.sizePolicy().hasHeightForWidth())
        self.label_pretest.setSizePolicy(sizePolicy)
        self.label_pretest.setObjectName("label_pretest")
        self.verticalLayout_2.addWidget(self.label_pretest)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.detail = QtWidgets.QTextBrowser(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detail.sizePolicy().hasHeightForWidth())
        self.detail.setSizePolicy(sizePolicy)
        self.detail.setObjectName("detail")
        self.horizontalLayout_4.addWidget(self.detail)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.gridLayout.addWidget(self.widget, 1, 0, 1, 1)

        self.retranslateUi(item)
        QtCore.QMetaObject.connectSlotsByName(item)

    def retranslateUi(self, item):
        _translate = QtCore.QCoreApplication.translate
        item.setWindowTitle(_translate("item", "Form"))
        self.label_num.setText(_translate("item", "No."))
        self.lable_university.setText(_translate("item", "University"))
        self.label_level.setText(_translate("item", "level"))
        self.label_condition.setText(_translate("item", "condition"))
        self.label_score.setText(_translate("item", "score"))
        self.label_evaluation.setText(_translate("item", "evaluation"))
        self.label_proCode.setText(_translate("item", "proCode"))
        self.label_proName.setText(_translate("item", "proName"))
        self.label_school.setText(_translate("item", "School"))
        self.label_retest.setText(_translate("item", "retest"))
        self.label_pretest.setText(_translate("item", "preliminary test"))

